import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';

export const metadata: Metadata = {
  title: "Beer World",
  description: "Generated by a beer dreamer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
      <AppRouterCacheProvider>
        
        {children}

      </AppRouterCacheProvider>
      </body>
    </html>
  );
}
